### ISSUE TITLE
Weird configuration for dev_server.manifest_host in Rails config

### ISSUE THREAD

**Issue by govorov** [mipearson/webpack-rails#56]
Hi.
Please add information about Rails configuration options available.
It tooks me some time to find a proper way to configure rails with webpack host on 0.0.0.0.
It is not clear without analyzing sources.
And I think it's reasonable to set manifest_host/port default value to something like
`proc { config.webpack.dev_server.host ||= 'localhost' }`
instead of `localhost`, because in most cases dev_server.host and manifest_server.host are equal.
Regards.

**Comment by tranquilize** [comment]
I had trouble getting my configs working correctly with Docker, but it's working now. Here's my setup in case anyone else is experiencing something similar:

1) My default generated `webpack.config.js` is untouched.
2) I created `config/initializers/webpack.rb`:
```
Rails.application.configure do
  config.webpack.dev_server.manifest_host = ENV['WEBPACK_REMOTE_HOST']
  config.webpack.dev_server.manifest_port = ENV['WEBPACK_REMOTE_PORT']
end
```
3) I added a `webpack` container to my `docker-compose.yml`:
```
  webpack:
    build: <project location>
    container_name: webpack
    command: ./node_modules/.bin/webpack-dev-server --config config/webpack.config.js --host '0.0.0.0'
    volumes:
      - <host location>:<container location>
    ports:
      - '3808:3808'
```
