### ISSUE TITLE
Loading images with rails helpers

### ISSUE THREAD

**Issue by Matt-Butler** [mipearson/webpack-rails#61]
What is the recommended way of referencing images with webpack-rails?

Is it possible to use something like this?
```haml
= image_tag *webpack_asset_paths('my-image', extension: 'png')
```

**Comment by mipearson** [comment]
I don't know, to be honest. I haven't played with images in webpack. Give it a go and see!

**Comment by Matt-Butler** [comment]
I think I understand the issue now. My images are not part of the assetsByChunkName attribute in the manifest.json file. This helper will not find my image assets: `*webpack_asset_paths('file', extension: 'png')`


manifest.json 
```
  "assetsByChunkName":{
      "file":[
         "file-554ffb8dcc2a3d701ac2.js",
         "file.css"
      ]
   },
```


There are two potential options:
1) Figure out how to add images to the assetsByChunkName attribute in manifest.json
2) Find out how to push my assets onto the path variable
 https://github.com/mipearson/webpack-rails/blob/5575507c1043de984b43f984eb59d5ad980f1b87/lib/webpack/rails/manifest.rb#L31

**Comment by Matt-Butler** [comment]
I found another work around by just making a css class for every image. I am also using the webpack url/file loader.

```html
<div class="graphic" />
```

```css
.graphic {
  background-image: url('./file.png');
  background-repeat: no-repeat;
  background-size: contain;
  width: 6rem;
  height: 6rem;
}
```
